services:
  postgresdb:
    image: postgres
    container_name: ecoleta_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ecoleta
    ports:
      - "5432:5432"